# This file is generated by gyp; do not edit.

export builddir_name ?= ./system_wrappers/out
.PHONY: all
all:
	$(MAKE) -C .. system_wrappers field_trial_default metrics_default system_wrappers_default
